### ISSUE TITLE
Question about the number of synthetic language demonstrations 

### ISSUE THREAD

**Issue by Gasoonjia** [alexpashevich/E.T.#2]
Thanks for your great work!

I wanna ask why the number of synthetic language demonstrations is not equal to the number of expert trajectories in train split?
Since each trajectory corresponds to a single PDDL, and your synthetic language demonstration is just generated from PDDL, I supposed that the number of synthetic language demonstrations would be just the same as the number of expert trajectories in train split. However, the number of synthetic language instructions is about five times larger than the expert trajectories.
Is there anything I misunderstood or are you using other methods of data augmentation?
Thanks for your help!

**Comment by alexpashevich** [comment]
Hi,

Thank you for your interest in our work. There are two different things: generating novel trajectories and replaying existing trajectories. In the first case, we randomly sample task parameters. In the second case, we take existing task parameters. For synthetic language demonstrations (e.g. generating novel trajectories), we use [this script](https://github.com/alexpashevich/E.T./blob/master/alfred/gen/generate_trajs.py). The script [spawns multiple threads](https://github.com/alexpashevich/E.T./blob/2e8660e8517d2f5b5baf1170bcd9d3882d21838f/alfred/gen/generate_trajs.py#L730) and [randomly samples task parameters](https://github.com/alexpashevich/E.T./blob/master/alfred/gen/generate_trajs.py#L59). The script is almost identical to the original script provided by ALFRED authors, you can read more about the data generation [here](https://github.com/askforalfred/alfred/tree/master/gen). Talking about replaying existing trajectories, we do it using [this script](https://github.com/alexpashevich/E.T./blob/master/alfred/gen/render_trajs.py) in order to record an LMDB dataset used later for training. Feel free to also check Appendix A.2 of [our paper](https://arxiv.org/pdf/2105.06453.pdf) where we compare agents trained on synthetic dataset of different sizes.

Hope this helps!
