### ISSUE TITLE
Share 45k synthetic trajectories

### ISSUE THREAD

**Issue by quangvnai** [alexpashevich/E.T.#3]
Thank you @alexpashevich for your great work.
When I followed your guide to `Generate 45K trajectories with alfred.gen.generate_trajs`, it mostly failed to generate trajectories in order to reproduce the result. 
Rather than sharing the entire `raw images`, would you just share the `traj_data.json` with us? I think the total size of such files for 45k trajectories is around 3 GB. From these files, we can render the images easily. 

Thank you so much!

**Comment by alexpashevich** [comment]
Hi Van-Quang,

Thank you for you interest in our work and excuse us for the delay with the reply. The fails that you observed are the expected behavior of the generate_trajs.py script.

You can download the tar.gz arxiv containing 45K trajectories using the following command:
`wget http://pascal.inrialpes.fr/data2/apashevi/json_synth_2.1.0.tar.gz`

Then you should be able to render the trajectories with render_trajs.py. Please let us know if you have any problems using it.

Best,
Alex

**Comment by quangvnai** [comment]
@alexpashevich Thank you a lot for your extra work to share the link. However, I can't access the shared link so far. Could you check it again?

**Comment by alexpashevich** [comment]
Hi @davidnvq ,

I updated my first answer with a wget command instead of a direct link from the browser. There seems to be a problem with the https protocol that I previously specified.

Best,
Alex

**Comment by quangvnai** [comment]
Great!  I can now download it successfully.  Many thanks to you @alexpashevich

**Comment by joeyy5588** [comment]
Hi @alexpashevich, I got 403 error when try to access the link you provided. Can you share it again? Thank you!

**Comment by alexpashevich** [comment]
UPD:
The trajectories are now can be found here:
https://drive.google.com/file/d/1RqYtm8ZU2xbef3OPJ5LKESjatodRVDPE/view?usp=sharing
